server:
  port: 8089
spring:
  application:
    name: EUREKA-SERVER-LOCAL
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://localhost:8089/eureka
