server:
  port: 8088
spring:
  application:
    name: APP-SERVICES-CONFIG
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ekosutrisno/spring-config-backed
          search-paths:
            - '*service'
          skip-ssl-validation: true
          timeout: 5

          #username:
          #password:

#Ureka config
eureka:
  instance:
    instance-id: APP-SERVICES-CONFIG
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 2
    prefer-ip-address: true
    secure-port: ${server.port}
    status-page-url: http://${eureka.instance.hostname}:${server.port}/actuator
    virtual-host-name: service-zuul-gateway
    hostname: localhost
    ip-address: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8089/eureka/

